### ISSUE TITLE
color scheme works in Gvim but not in vim on windows

### ISSUE THREAD

**Issue by mokchhya** [zeis/vim-kolor#10]
I have posted a question in [SO](http://stackoverflow.com/questions/32495714/colorscheme-kolor-not-working-on-vim-opened-from-powershell).

Not sure whether this is an issue or i have configured it incorrectly.

**Comment by zeis** [comment]
The default terminal on Windows supports a very limited range of colors. Because of this limitation most color schemes will "not work" in your terminal.
I would suggest you to use Gvim or a better terminal.
