### ISSUE TITLE
[Feature request] Light background option?

### ISSUE THREAD

**Issue by firecat53** [zeis/vim-kolor#9]
Just wondering if you happen to have created a version of this tuned for a light background? If not, feel free to close this. I'm wanting to work outside more this summer...and you did a great job on the dark scheme!

Thanks!
Scott

**Comment by zeis** [comment]
Thank you for appreciating the color scheme.

This color scheme was conceived with a dark background in mind. So, it's unlikely that the same colors will look nice on a light background without any adaptations.

There is one thing that one could try though: inverting all the colors! (...however, this implies that you get a completely different color scheme).
Although I haven't tried it myself, intuitively, proportions are kept constant and the result should still be nice. If you are willing to try this (and have time to!), here's what a quick Google search returns about inverting colors:
http://stackoverflow.com/questions/6961725/algorithm-for-calculating-inverse-color

**Comment by firecat53** [comment]
Thanks for the tip. Given time crunch...for now I found the [Github](http://www.vim.org/scripts/script.php?script_id=2855) theme which seems to be pretty usable. Thanks again for the great theme....think I started using it right after you released :)

Scott
